symbols = ['BTC/USDT', 'ETH/USDT', 'BNB/USDT', 'XRP/USDT', 'ADA/USDT', 'SOL/USDT', 'AVAX/USDT', 'LUNA/USDT', 'DOGE/USDT', 'DOT/USDT', 
    '1000SHIB/USDT', 'MATIC/USDT', 'LTC/USDT', 'ATOM/USDT', 'LINK/USDT', 'NEAR/USDT', 'UNI/USDT', 'TRX/USDT', 'ALGO/USDT', 'BCH/USDT', 
    'MANA/USDT', 'XLM/USDT', 'FTM/USDT', 'HBAR/USDT', 'ICP/USDT', 'ETC/USDT', 'EGLD/USDT', 'FIL/USDT', 'KLAY/USDT', 'AXS/USDT', 
    'THETA/USDT', 'XTZ/USDT', 'XMR/USDT', 'HNT/USDT', 'EOS/USDT', 'FLOW/USDT', 'GALA/USDT', 'AAVE/USDT', 'ONE/USDT', 'GRT/USDT']

long_k, short_k = 0.5, 0.5

time_slice = [(i+1)*30 for i in range(24)]